#include "bd_widget_editor.h"
#include "widget_ext.h"
#include "bd_draw.h"
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/*
 * Rich-text editor widget. Plain UTF-8 text in a growable buffer with the
 * BD_TEXT_AREA editing model (caret nav, newline, backspace/delete, click,
 * scroll), plus a list of style runs over byte ranges that the renderer draws
 * segment by segment (per-run fg/bg, underline, strikeout, faux-bold,
 * super/subscript). A row-oriented API and a lock complete the editor.
 *
 * Made by a machine. PUBLIC DOMAIN (CC0-1.0)
 */

/* Style runs are tagged with a layer; composition (e_style_at) resolves
 * attribute-by-attribute in ascending layer order (higher layer wins), so a
 * find highlight can tint the background over syntax colour without erasing
 * it. Within a layer, a later run wins. */
enum {
	E_LAYER_SYNTAX = 0,  /* regenerated by a syntax pass */
	E_LAYER_USER,        /* app style_span / highlight_* */
	E_LAYER_FIND,        /* every find match */
	E_LAYER_MARK,        /* the current find match / a transient mark */
	E_N_LAYERS,
};

struct erun { int start, end; int layer; bd_rich_style style; };

#define AC_MAX     10   /* max completions shown at once */
#define AC_TEXTLEN 64
#define AC_DETLEN  24

#define FIND_BG      0x5A5322FFu   /* every match: muted amber wash */
#define FIND_CUR_BG  0xB5791EFFu   /* the current match: brighter amber */

struct editor {
	char  *buf;
	int    len, cap;
	int    cursor;
	int    sel_anchor;      /* selection anchor byte offset, -1 = none */
	float  scroll_x;
	int    scroll_y;
	int    locked;
	int    mono;            /* fixed-width face (default on) */
	int    enter_submits;   /* plain Enter submits instead of inserting \n */
	bd_callback_fn on_submit;
	void  *on_submit_data;
	struct erun *runs;
	int    nrun, runcap;

	/* find / replace */
	char  *find_needle;     /* current search (malloc'd), NULL = inactive */
	unsigned find_flags;    /* BD_FIND_* */
	int    find_cur;        /* index of the current match, -1 = none */
	int    find_n;          /* match count at the last find */
	int   *find_starts;     /* byte offset of each match */
	int    find_startcap;

	/* autocomplete */
	bd_completer_fn ac_fn;
	void  *ac_user;
	int    ac_min;          /* auto-trigger prefix length (default 2) */
	int    ac_open;
	int    ac_anchor;       /* byte offset where the current word starts */
	int    ac_sel;          /* highlighted item */
	int    ac_n;            /* item count */
	char   ac_text[AC_MAX][AC_TEXTLEN];
	char   ac_detail[AC_MAX][AC_DETLEN];
};

static int editor_type;

/* ------------------------------------------------------------------ */
/* utf-8                                                              */
/* ------------------------------------------------------------------ */

static int e_cont(unsigned char c) { return (c & 0xC0) == 0x80; }

static int
e_prev(const char *s, int p)
{
	if (p <= 0) return 0;
	p--;
	while (p > 0 && e_cont((unsigned char)s[p])) p--;
	return p;
}

static int
e_next(const char *s, int len, int p)
{
	if (p >= len) return len;
	p++;
	while (p < len && e_cont((unsigned char)s[p])) p++;
	return p;
}

static int
e_encode(unsigned cp, char *o)
{
	if (cp < 0x80)    { o[0] = (char)cp; return 1; }
	if (cp < 0x800)   { o[0] = (char)(0xC0|(cp>>6)); o[1]=(char)(0x80|(cp&0x3F)); return 2; }
	if (cp < 0x10000) { o[0]=(char)(0xE0|(cp>>12)); o[1]=(char)(0x80|((cp>>6)&0x3F)); o[2]=(char)(0x80|(cp&0x3F)); return 3; }
	o[0]=(char)(0xF0|(cp>>18)); o[1]=(char)(0x80|((cp>>12)&0x3F));
	o[2]=(char)(0x80|((cp>>6)&0x3F)); o[3]=(char)(0x80|(cp&0x3F));
	return 4;
}

/* ------------------------------------------------------------------ */
/* buffer + style-run editing                                         */
/* ------------------------------------------------------------------ */

static int
e_ensure(struct editor *e, int need)
{
	if (need <= e->cap) return 1;
	int c = e->cap ? e->cap * 2 : 256;
	while (c < need) c *= 2;
	char *p = realloc(e->buf, (size_t)c);
	if (!p) return 0;
	e->buf = p;
	e->cap = c;
	return 1;
}

/* shift one byte offset across an edit at [off,off+dellen) growing by delta */
static int
e_shift(int x, int off, int dellen, int delta)
{
	if (x <= off) return x;
	if (x >= off + dellen) return x + delta;
	return off;
}

/* replace dellen bytes at off with ins[0..inslen); fixes runs + cursor */
static void
e_splice(struct editor *e, int off, int dellen, const char *ins, int inslen)
{
	if (off < 0) off = 0;
	if (off > e->len) off = e->len;
	if (dellen < 0) dellen = 0;
	if (off + dellen > e->len) dellen = e->len - off;

	int newlen = e->len - dellen + inslen;
	if (!e_ensure(e, newlen + 1)) return;
	memmove(e->buf + off + inslen, e->buf + off + dellen,
	    (size_t)(e->len - off - dellen));
	if (inslen) memcpy(e->buf + off, ins, (size_t)inslen);
	e->len = newlen;
	e->buf[e->len] = '\0';

	int delta = inslen - dellen;
	for (int i = 0; i < e->nrun; i++) {
		e->runs[i].start = e_shift(e->runs[i].start, off, dellen, delta);
		e->runs[i].end   = e_shift(e->runs[i].end, off, dellen, delta);
	}
	/* drop emptied runs */
	int w = 0;
	for (int i = 0; i < e->nrun; i++)
		if (e->runs[i].end > e->runs[i].start)
			e->runs[w++] = e->runs[i];
	e->nrun = w;

	e->cursor = e_shift(e->cursor, off, dellen, delta);
	if (e->cursor > e->len) e->cursor = e->len;
}

/* ------------------------------------------------------------------ */
/* rows                                                               */
/* ------------------------------------------------------------------ */

static int
e_row_count(const struct editor *e)
{
	int n = 1;
	for (int i = 0; i < e->len; i++)
		if (e->buf[i] == '\n') n++;
	return n;
}

/* byte offset of the start of `row` (clamped to len) */
static int
e_row_start(const struct editor *e, int row)
{
	int p = 0;
	for (int r = 0; r < row; r++) {
		while (p < e->len && e->buf[p] != '\n') p++;
		if (p < e->len) p++;
		else break;
	}
	return p;
}

static int
e_row_end(const struct editor *e, int off)
{
	while (off < e->len && e->buf[off] != '\n') off++;
	return off;
}

/* start of the line containing pos (scan back to after the previous \n) */
static int
e_line_start(const struct editor *e, int pos)
{
	while (pos > 0 && e->buf[pos - 1] != '\n') pos--;
	return pos;
}

static int
e_line_index(const struct editor *e, int pos)
{
	int n = 0;
	for (int i = 0; i < pos; i++)
		if (e->buf[i] == '\n') n++;
	return n;
}

/* ------------------------------------------------------------------ */
/* style runs                                                         */
/* ------------------------------------------------------------------ */

static void
e_add_run(struct editor *e, int s, int en, int layer, bd_rich_style st)
{
	if (s < 0) s = 0;
	if (en > e->len) en = e->len;
	if (en <= s) return;
	if (e->nrun == e->runcap) {
		int c = e->runcap ? e->runcap * 2 : 8;
		struct erun *p = realloc(e->runs, (size_t)c * sizeof *p);
		if (!p) return;
		e->runs = p;
		e->runcap = c;
	}
	e->runs[e->nrun++] = (struct erun){ s, en, layer, st };
}

/* Combined style at byte pos: compose overlapping runs attribute by
 * attribute. flags OR together; fg and bg each take the value from the
 * highest-layer run that sets them (non-zero), ties broken by insertion
 * order. So a find highlight (bg only, high layer) tints over a syntax
 * colour without clearing the foreground. */
static bd_rich_style
e_style_at(const struct editor *e, int pos)
{
	bd_rich_style st = { 0, 0, 0 };
	int fg_layer = -1, bg_layer = -1;
	for (int i = 0; i < e->nrun; i++) {
		const struct erun *r = &e->runs[i];
		if (r->start > pos || pos >= r->end)
			continue;
		st.flags |= r->style.flags;
		if (r->style.fg && r->layer >= fg_layer) {
			st.fg = r->style.fg; fg_layer = r->layer;
		}
		if (r->style.bg && r->layer >= bg_layer) {
			st.bg = r->style.bg; bg_layer = r->layer;
		}
	}
	return st;
}

static int
e_style_eq(bd_rich_style a, bd_rich_style b)
{
	return a.flags == b.flags && a.fg == b.fg && a.bg == b.bg;
}

/* ------------------------------------------------------------------ */
/* measuring                                                          */
/* ------------------------------------------------------------------ */

/* bd_draw font flags for a run's style, plus the editor's base (mono) face */
static int
e_font(const struct editor *e, bd_rich_style st)
{
	int f = e->mono ? BD_FONT_MONO : 0;
	if (st.flags & BD_RT_BOLD)   f |= BD_FONT_BOLD;
	if (st.flags & BD_RT_ITALIC) f |= BD_FONT_ITALIC;
	return f;
}

/* width of buf[a,b) drawn in `font` */
static float
e_seg_w(const struct editor *e, int a, int b, int font)
{
	char tmp[1024];
	int n = b - a;
	if (n <= 0) return 0.0f;
	if (n >= (int)sizeof tmp) n = (int)sizeof tmp - 1;
	memcpy(tmp, e->buf + a, (size_t)n);
	tmp[n] = '\0';
	return bd_draw_text_width_styled(tmp, font);
}

/* style-aware width of buf[a,b): segment by run, measure each in its face */
static float
e_span_px(const struct editor *e, int a, int b)
{
	float w = 0.0f;
	int p = a;
	while (p < b) {
		bd_rich_style st = e_style_at(e, p);
		int q = e_next(e->buf, b, p);
		while (q < b && e_style_eq(e_style_at(e, q), st))
			q = e_next(e->buf, b, q);
		w += e_seg_w(e, p, q, e_font(e, st));
		p = q;
	}
	return w;
}

static int
e_col_at_px(const struct editor *e, int start, int end, float target)
{
	int pos = start;
	float w = 0.0f;
	while (pos < end) {
		int nx = e_next(e->buf, end, pos);
		float cw = e_seg_w(e, pos, nx, e_font(e, e_style_at(e, pos)));
		if (w + cw * 0.5f >= target) return pos;
		w += cw;
		pos = nx;
	}
	return end;
}

static int
e_line_h(const struct editor *e)
{
	int h = (int)bd_draw_line_height_styled(e->mono ? BD_FONT_MONO : 0);
	return h > 0 ? h : 14;
}

/* ------------------------------------------------------------------ */
/* class hooks                                                        */
/* ------------------------------------------------------------------ */

static void
editor_init(bd_id id, void *state)
{
	struct editor *e = state;
	e->mono = 1;            /* a code/music editor wants fixed-width by default */
	e->sel_anchor = -1;
	e->find_cur = -1;
	e->ac_min = 2;          /* auto-complete after this many word chars */
	bd_set(id, BD_PREF_W_I, 280, BD_PREF_H_I, 140, BD_PAD_I, 4, BD_END);
}

static void
editor_destroy(bd_id id, void *state)
{
	(void)id;
	struct editor *e = state;
	free(e->buf);
	free(e->runs);
	free(e->find_needle);
	free(e->find_starts);
	e->buf = NULL;
	e->runs = NULL;
	e->find_needle = NULL;
	e->find_starts = NULL;
}

/* draw one line [a,b) at (x0,top), segmenting by style run */
static void
editor_draw_line(struct editor *e, int a, int b, float x0, int top,
    const bd_theme *th)
{
	int lh = e_line_h(e);
	float penx = x0;
	int seg = a;
	while (seg < b) {
		bd_rich_style st = e_style_at(e, seg);
		int q = e_next(e->buf, b, seg);
		while (q < b && e_style_eq(e_style_at(e, q), st))
			q = e_next(e->buf, b, q);

		char tmp[1024];
		int n = q - seg;
		if (n >= (int)sizeof tmp) n = (int)sizeof tmp - 1;
		memcpy(tmp, e->buf + seg, (size_t)n);
		tmp[n] = '\0';
		int font = e_font(e, st);          /* mono + true bold/italic face */
		float w = bd_draw_text_width_styled(tmp, font);

		uint32_t fg = st.fg ? st.fg : th->text;
		int y = top;
		if (st.flags & BD_RT_SUPER) y -= lh / 4;
		else if (st.flags & BD_RT_SUB) y += lh / 4;

		if (st.bg)
			bd_draw_rect(penx, (float)top, w, (float)lh, st.bg);
		bd_draw_text_styled(tmp, penx, (float)y, fg, font);
		if (st.flags & BD_RT_UNDERLINE)
			bd_draw_rect(penx, (float)(y + lh - 2), w, 1.0f, fg);
		if (st.flags & BD_RT_STRIKE)
			bd_draw_rect(penx, (float)(y + lh / 2), w, 1.0f, fg);

		penx += w;
		seg = q;
	}
}

static void
editor_render(bd_id id, void *state)
{
	struct editor *e = state;
	const bd_theme *th = bd_gui_theme();
	const bd_backend *be = bd_backend_get();
	int focused = (bd_focused() == id);

	int x, y, w, h;
	bd_widget_rect(id, &x, &y, &w, &h);
	bd_draw_rect(x, y, w, h, th->press);
	bd_draw_rect_lines(x, y, w, h, focused ? th->focus : th->border);

	int pad = bd_get_i(id, BD_PAD_I);
	int ix = x + pad, iy = y + pad;
	int iw = w - 2 * pad, ih = h - 2 * pad;
	int lh = e_line_h(e);

	/* caret line/x, then keep it in view */
	int cls = e_line_start(e, e->cursor);
	int caret_line = e_line_index(e, e->cursor);
	float caret_px = e_span_px(e, cls, e->cursor);
	int caret_top = caret_line * lh;
	if (caret_top - e->scroll_y < 0) e->scroll_y = caret_top;
	if (caret_top + lh - e->scroll_y > ih) e->scroll_y = caret_top + lh - ih;
	if (e->scroll_y < 0) e->scroll_y = 0;
	if (caret_px - e->scroll_x > (float)iw) e->scroll_x = caret_px - (float)iw;
	if (caret_px - e->scroll_x < 0.0f) e->scroll_x = caret_px;
	if (e->scroll_x < 0.0f) e->scroll_x = 0.0f;

	bd_draw_flush();
	be->scissor(ix, iy, iw, ih);

	/* selection span (sorted); a per-line rect is drawn behind the text */
	int has_sel = focused && e->sel_anchor >= 0 && e->sel_anchor != e->cursor;
	int s0 = e->sel_anchor < e->cursor ? e->sel_anchor : e->cursor;
	int s1 = e->sel_anchor < e->cursor ? e->cursor : e->sel_anchor;

	int li = 0, pos = 0;
	for (;;) {
		int le = e_row_end(e, pos);
		int top = iy + li * lh - e->scroll_y;
		if (top + lh >= iy && top <= iy + ih) {
			if (has_sel && s0 <= le && s1 >= pos) {
				int a = s0 > pos ? s0 : pos;
				int b = s1 < le ? s1 : le;
				float xa = e_span_px(e, pos, a);
				float xb = e_span_px(e, pos, b);
				int hx = ix + (int)(xa - e->scroll_x);
				int hw = (int)(xb - xa);
				if (s1 > le) hw += 6;   /* selected newline stub */
				bd_draw_rect((float)hx, (float)top, (float)hw,
				    (float)lh, th->select);
			}
			editor_draw_line(e, pos, le, (float)ix - e->scroll_x, top, th);
		}
		if (le >= e->len) break;
		pos = le + 1;
		li++;
	}

	if (focused && !e->locked) {
		double t = bd_time();
		if (((int)(t * 2.0)) % 2 == 0) {
			int cx = ix + (int)(caret_px - e->scroll_x);
			int cy = iy + caret_top - e->scroll_y;
			bd_draw_rect((float)cx, (float)cy, 2.0f, (float)lh, th->text_hi);
		}
	}

	bd_draw_flush();
	be->scissor_off();

	/* autocomplete popup: a floating list anchored under the word, drawn
	 * after the text scissor so it can overlay the following lines */
	if (focused && e->ac_open && e->ac_n > 0) {
		int prow = (int)bd_draw_line_height() + 4;
		float ws_px = e_span_px(e, cls, e->ac_anchor);   /* word-start x */
		int px = ix + (int)(ws_px - e->scroll_x);
		int caret_y = iy + caret_top - e->scroll_y;

		int pw = 140;
		for (int i = 0; i < e->ac_n; i++) {
			int wt = (int)bd_draw_text_width(e->ac_text[i]);
			int wd = e->ac_detail[i][0]
			    ? (int)bd_draw_text_width(e->ac_detail[i]) + 20 : 0;
			int need = wt + wd + 16;
			if (need > pw) pw = need;
		}
		if (pw > w - 8) pw = w - 8;
		int ph = e->ac_n * prow + 2;
		if (px + pw > x + w - 2) px = x + w - 2 - pw;
		if (px < x + 2) px = x + 2;
		int py = caret_y + lh;                     /* below the caret ... */
		if (py + ph > y + h - 2) py = caret_y - ph; /* ... or flip above */
		if (py < y + 2) py = y + 2;

		bd_draw_flush();
		bd_draw_rect((float)px, (float)py, (float)pw, (float)ph, th->widget);
		bd_draw_rect_lines((float)px, (float)py, (float)pw, (float)ph, th->border);
		int base = (prow - (int)bd_draw_line_height()) / 2;
		for (int i = 0; i < e->ac_n; i++) {
			int ry = py + 1 + i * prow;
			if (i == e->ac_sel)
				bd_draw_rect((float)(px + 1), (float)ry,
				    (float)(pw - 2), (float)prow, th->select);
			bd_draw_text(e->ac_text[i], (float)(px + 6),
			    (float)(ry + base), th->text);
			if (e->ac_detail[i][0]) {
				float dw = bd_draw_text_width(e->ac_detail[i]);
				bd_draw_text(e->ac_detail[i],
				    (float)(px + pw - 6) - dw, (float)(ry + base),
				    th->border);
			}
		}
		bd_draw_flush();
	}
}

/* ------------------------------------------------------------------ */
/* editing helpers                                                    */
/* ------------------------------------------------------------------ */

static void
editor_insert(struct editor *e, unsigned cp)
{
	if (e->locked) return;
	char enc[4];
	int n = e_encode(cp, enc);
	int off = e->cursor;
	e_splice(e, off, 0, enc, n);
	e->cursor = off + n;
}

/* ------------------------------------------------------------------ */
/* autocomplete                                                       */
/* ------------------------------------------------------------------ */

static int
ac_is_word(unsigned char c)
{
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
	    (c >= '0' && c <= '9') || c == '_';
}

/* Byte offset where the identifier ending at the caret starts. */
static int
ac_word_start(const struct editor *e)
{
	int p = e->cursor;
	while (p > 0 && ac_is_word((unsigned char)e->buf[p - 1]))
		p--;
	return p;
}

static void
ac_close(struct editor *e)
{
	e->ac_open = 0;
	e->ac_n = 0;
}

/* Recompute the prefix before the caret and (re-)query the provider. Opens the
 * popup when the prefix is long enough and the provider returns items. */
static void
ac_query(bd_id id, struct editor *e)
{
	if (!e->ac_fn || e->locked) { ac_close(e); return; }
	int start = ac_word_start(e);
	int plen = e->cursor - start;
	if (plen < e->ac_min || plen >= AC_TEXTLEN) {
		ac_close(e);
		return;
	}
	char prefix[AC_TEXTLEN];
	memcpy(prefix, e->buf + start, (size_t)plen);
	prefix[plen] = '\0';

	bd_completion items[AC_MAX];
	memset(items, 0, sizeof items);
	int n = e->ac_fn(id, prefix, items, AC_MAX, e->ac_user);
	if (n < 0) n = 0;
	if (n > AC_MAX) n = AC_MAX;
	for (int i = 0; i < n; i++) {
		e->ac_text[i][0] = '\0';
		e->ac_detail[i][0] = '\0';
		if (items[i].text) {
			strncpy(e->ac_text[i], items[i].text, AC_TEXTLEN - 1);
			e->ac_text[i][AC_TEXTLEN - 1] = '\0';
		}
		if (items[i].detail) {
			strncpy(e->ac_detail[i], items[i].detail, AC_DETLEN - 1);
			e->ac_detail[i][AC_DETLEN - 1] = '\0';
		}
	}
	e->ac_n = n;
	e->ac_anchor = start;
	if (e->ac_sel >= n)
		e->ac_sel = 0;
	e->ac_open = n > 0;
}

/* Replace the current word fragment with the highlighted completion. */
static void
ac_accept(struct editor *e)
{
	if (!e->ac_open || e->ac_sel < 0 || e->ac_sel >= e->ac_n || e->locked) {
		ac_close(e);
		return;
	}
	const char *t = e->ac_text[e->ac_sel];
	int tn = (int)strlen(t);
	int start = e->ac_anchor;
	e_splice(e, start, e->cursor - start, t, tn);
	e->cursor = start + tn;
	ac_close(e);
}

/* Sorted selection range [*a,*b); 0 when there is no (non-empty) selection. */
static int
ed_sel_range(struct editor *e, int *a, int *b)
{
	if (e->sel_anchor < 0 || e->sel_anchor == e->cursor)
		return 0;
	*a = e->sel_anchor < e->cursor ? e->sel_anchor : e->cursor;
	*b = e->sel_anchor < e->cursor ? e->cursor : e->sel_anchor;
	return 1;
}

/* Delete the selection (if any), leaving the caret at its start. */
static void
ed_del_sel(struct editor *e)
{
	int a, b;
	if (e->locked || !ed_sel_range(e, &a, &b))
		return;
	e_splice(e, a, b - a, NULL, 0);
	e->cursor = a;
	e->sel_anchor = -1;
}

/* Copy the selection (if any) to the system clipboard. */
static void
ed_copy_sel(struct editor *e)
{
	int a, b;
	const bd_backend *be = bd_backend_get();
	if (!be || !be->clipboard_set || !ed_sel_range(e, &a, &b))
		return;
	char *tmp = malloc((size_t)(b - a) + 1);
	if (!tmp)
		return;
	memcpy(tmp, e->buf + a, (size_t)(b - a));
	tmp[b - a] = '\0';
	be->clipboard_set(tmp);
	free(tmp);
}

/* Byte offset at the pixel point (px,py), mapping through scroll and line. */
static int
editor_offset_at(struct editor *e, bd_id id, int px, int py)
{
	int x, y, w, h;
	bd_widget_rect(id, &x, &y, &w, &h);
	int pad = bd_get_i(id, BD_PAD_I);
	int ix = x + pad, iy = y + pad;
	int lh = e_line_h(e);
	int line = (py - iy + e->scroll_y) / (lh > 0 ? lh : 1);
	if (line < 0)
		line = 0;
	int pos = e_row_start(e, line);
	int le = e_row_end(e, pos);
	return e_col_at_px(e, pos, le, (float)(px - ix) + e->scroll_x);
}

static int
editor_event(bd_id id, void *state, const bd_event *ev)
{
	struct editor *e = state;
	int lh = e_line_h(e);

	switch (ev->type) {
	case BD_EV_MOUSE_SCROLL:
		e->scroll_y -= (int)(ev->scroll_dy * (float)lh);
		if (e->scroll_y < 0) e->scroll_y = 0;
		return 1;

	case BD_EV_MOUSE_DOWN: {
		if (ev->button != BD_MOUSE_LEFT) return 1;
		int prev = e->sel_anchor;
		e->cursor = editor_offset_at(e, id, ev->x, ev->y);
		/* shift-click extends from the old anchor; a plain press
		 * clears the selection, a drag anchors lazily on the first move */
		if ((ev->mods & BD_MOD_SHIFT) && prev >= 0)
			e->sel_anchor = prev;
		else
			e->sel_anchor = -1;
		return 1;
	}
	case BD_EV_MOUSE_MOVE:
		/* drag-select: anchor at the press caret on the first move */
		if (e->sel_anchor < 0)
			e->sel_anchor = e->cursor;
		e->cursor = editor_offset_at(e, id, ev->x, ev->y);
		return 1;
	case BD_EV_MOUSE_UP:
		return 1;

	case BD_EV_CHAR:
		if (ev->codepoint >= 32) {
			ed_del_sel(e);   /* typing replaces a selection */
			editor_insert(e, ev->codepoint);
			/* a word char (re-)queries; anything else dismisses */
			if (e->ac_fn && ev->codepoint < 128 &&
			    ac_is_word((unsigned char)ev->codepoint))
				ac_query(id, e);
			else
				ac_close(e);
		}
		return 1;

	case BD_EV_TEXT_COMMIT:        /* IME / compose / dead-key commit */
		if (!e->locked && ev->text) {
			int n = (int)strlen(ev->text);
			e_splice(e, e->cursor, 0, ev->text, n);
			e->cursor += n;
			if (e->ac_fn)
				ac_query(id, e);
		}
		return 1;

	case BD_EV_KEY_DOWN:
		break;
	default:
		return 0;
	}

	/* autocomplete popup steals navigation/accept keys while open */
	if (e->ac_open) {
		switch (ev->key) {
		case BD_KEY_DOWN:
			e->ac_sel = (e->ac_sel + 1) % e->ac_n;
			return 1;
		case BD_KEY_UP:
			e->ac_sel = (e->ac_sel - 1 + e->ac_n) % e->ac_n;
			return 1;
		case BD_KEY_ENTER:
			ac_accept(e);
			return 1;
		case BD_KEY_ESCAPE:
			ac_close(e);
			return 1;      /* consume, keep focus */
		case BD_KEY_BACKSPACE:
			break;         /* fall through: delete, then re-query below */
		default:
			ac_close(e);   /* caret moves etc. dismiss, then act normally */
			break;
		}
	}

	/* key handling */
	int ls = e_line_start(e, e->cursor);
	int old_cursor = e->cursor;
	int shift = ev->mods & BD_MOD_SHIFT;
	switch (ev->key) {
	case BD_KEY_LEFT:
		e->cursor = e_prev(e->buf, e->cursor);
		break;
	case BD_KEY_RIGHT:
		e->cursor = e_next(e->buf, e->len, e->cursor);
		break;
	case BD_KEY_HOME:
		e->cursor = ls;
		break;
	case BD_KEY_END:
		e->cursor = e_row_end(e, e->cursor);
		break;
	case BD_KEY_UP: {
		if (ls == 0) { e->cursor = 0; break; }
		float gx = e_span_px(e, ls, e->cursor);
		int ps = e_line_start(e, ls - 1);
		e->cursor = e_col_at_px(e, ps, ls - 1, gx);
		break;
	}
	case BD_KEY_DOWN: {
		int le = e_row_end(e, e->cursor);
		if (le >= e->len) { e->cursor = e->len; break; }
		float gx = e_span_px(e, ls, e->cursor);
		int ns = le + 1, ne = e_row_end(e, ns);
		e->cursor = e_col_at_px(e, ns, ne, gx);
		break;
	}
	case BD_KEY_ENTER: {
		int mod = ev->mods & (BD_MOD_SHIFT | BD_MOD_CTRL);
		/* enter_submits: plain Enter submits, modified inserts a newline.
		 * default: Ctrl+Enter submits, everything else inserts a newline. */
		int submit = e->enter_submits ? (mod == 0) : (ev->mods & BD_MOD_CTRL);
		if (submit && e->on_submit)
			e->on_submit(id, e->on_submit_data);
		else {
			ed_del_sel(e);            /* replace any selection */
			editor_insert(e, '\n'); /* editor_insert honors the lock */
		}
		break;
	}
	case 'C':       /* Ctrl-C: copy selection */
		if (ev->mods & BD_MOD_CTRL) {
			ed_copy_sel(e);
			return 1;
		}
		return 0;
	case 'X':       /* Ctrl-X: cut selection */
		if (ev->mods & BD_MOD_CTRL) {
			ed_copy_sel(e);
			ed_del_sel(e);
			return 1;
		}
		return 0;
	case 'V':       /* Ctrl-V: paste at the cursor */
		if (ev->mods & BD_MOD_CTRL) {
			const bd_backend *be = bd_backend_get();
			const char *t = (!e->locked && be->clipboard_get)
			    ? be->clipboard_get() : NULL;
			if (t) {
				ed_del_sel(e);   /* replace any selection */
				int n = (int)strlen(t);
				e_splice(e, e->cursor, 0, t, n);
				e->cursor += n;
			}
			return 1;
		}
		return 0;
	case BD_KEY_BACKSPACE:
		if (e->sel_anchor >= 0 && e->sel_anchor != e->cursor) {
			ed_del_sel(e);
		} else if (!e->locked && e->cursor > 0) {
			int p = e_prev(e->buf, e->cursor);
			e_splice(e, p, e->cursor - p, NULL, 0);  /* cursor -> p */
		}
		if (e->ac_open)                  /* shrink the prefix, re-filter */
			ac_query(id, e);
		break;
	case BD_KEY_DELETE:
		if (e->sel_anchor >= 0 && e->sel_anchor != e->cursor) {
			ed_del_sel(e);
		} else if (!e->locked && e->cursor < e->len) {
			int nx = e_next(e->buf, e->len, e->cursor);
			e_splice(e, e->cursor, nx - e->cursor, NULL, 0);
		}
		break;
	case BD_KEY_ESCAPE:
		return 0;   /* let the toolkit drop focus */
	default:
		return 0;
	}
	/* selection: Shift extends across a caret move; a plain move clears it.
	 * Editing keys manage their own anchor above. */
	switch (ev->key) {
	case BD_KEY_LEFT: case BD_KEY_RIGHT: case BD_KEY_UP:
	case BD_KEY_DOWN: case BD_KEY_HOME: case BD_KEY_END:
		if (shift) {
			if (e->sel_anchor < 0)
				e->sel_anchor = old_cursor;
		} else {
			e->sel_anchor = -1;
		}
		break;
	default:
		break;
	}
	return 1;
}

static const bd_widget_class editor_class = {
	.name = "editor",
	.state_size = sizeof(struct editor),
	.init = editor_init,
	.destroy = editor_destroy,
	.render = editor_render,
	.event = editor_event,
};

/* ------------------------------------------------------------------ */
/* find / replace                                                     */
/* ------------------------------------------------------------------ */

static unsigned char
e_lc(unsigned char c)
{
	return (c >= 'A' && c <= 'Z') ? (unsigned char)(c + 32) : c;
}

/* Drop every run tagged `layer`, compacting the array. */
static void
e_clear_layer(struct editor *e, int layer)
{
	int w = 0;
	for (int i = 0; i < e->nrun; i++)
		if (e->runs[i].layer != layer)
			e->runs[w++] = e->runs[i];
	e->nrun = w;
}

/* Does the needle match at byte `pos`? (bounds already checked by caller) */
static int
e_match_at(const struct editor *e, int pos, const char *ndl, int nlen,
    unsigned flags)
{
	for (int i = 0; i < nlen; i++) {
		unsigned char a = (unsigned char)e->buf[pos + i];
		unsigned char b = (unsigned char)ndl[i];
		if (flags & BD_FIND_ICASE) { a = e_lc(a); b = e_lc(b); }
		if (a != b)
			return 0;
	}
	if (flags & BD_FIND_WORD) {
		if (pos > 0 && ac_is_word((unsigned char)e->buf[pos - 1]))
			return 0;
		if (pos + nlen < e->len &&
		    ac_is_word((unsigned char)e->buf[pos + nlen]))
			return 0;
	}
	return 1;
}

/* Remove the current-match mark and, if a match is current, add it back at
 * find_starts[find_cur]. */
static void
e_find_mark(struct editor *e)
{
	e_clear_layer(e, E_LAYER_MARK);
	if (e->find_cur < 0 || e->find_cur >= e->find_n || !e->find_needle)
		return;
	int nlen = (int)strlen(e->find_needle);
	int s = e->find_starts[e->find_cur];
	bd_rich_style st = { 0, 0, FIND_CUR_BG };
	e_add_run(e, s, s + nlen, E_LAYER_MARK, st);
}

/* Rescan the buffer for the stored needle: refill find_starts, re-add the
 * FIND-layer highlight for every match, and clamp find_cur. Does not move the
 * caret or re-mark (callers do). */
static void
e_find_rebuild(struct editor *e)
{
	e_clear_layer(e, E_LAYER_FIND);
	e_clear_layer(e, E_LAYER_MARK);
	e->find_n = 0;
	if (!e->find_needle || !e->find_needle[0]) {
		e->find_cur = -1;
		return;
	}
	int nlen = (int)strlen(e->find_needle);
	bd_rich_style st = { 0, 0, FIND_BG };
	for (int p = 0; p + nlen <= e->len; ) {
		if (!e_match_at(e, p, e->find_needle, nlen, e->find_flags)) {
			p++;
			continue;
		}
		if (e->find_n == e->find_startcap) {
			int c = e->find_startcap ? e->find_startcap * 2 : 16;
			int *ns = realloc(e->find_starts, (size_t)c * sizeof *ns);
			if (!ns)
				break;
			e->find_starts = ns;
			e->find_startcap = c;
		}
		e->find_starts[e->find_n++] = p;
		e_add_run(e, p, p + nlen, E_LAYER_FIND, st);
		p += nlen;                 /* non-overlapping matches */
	}
	if (e->find_n == 0)
		e->find_cur = -1;
	else if (e->find_cur < 0 || e->find_cur >= e->find_n)
		e->find_cur = 0;
}

/* Point the caret at the current match so render scrolls it into view. */
static void
e_find_reveal(struct editor *e)
{
	if (e->find_cur < 0 || e->find_cur >= e->find_n)
		return;
	e->cursor = e->find_starts[e->find_cur];
	e->sel_anchor = -1;
}

/* ------------------------------------------------------------------ */
/* public API                                                         */
/* ------------------------------------------------------------------ */

static struct editor *
editor_of(bd_id id)
{
	if (bd_widget_type(id) != editor_type) return NULL;
	return bd_widget_state(id);
}

bd_id
bd_editor_create(bd_id parent, ...)
{
	if (editor_type == 0)
		editor_type = bd_register_widget_class(&editor_class);
	va_list ap;
	va_start(ap, parent);
	bd_id id = bd_create_va(parent, editor_type, ap);
	va_end(ap);
	return id;
}

void
bd_editor_set_text(bd_id id, const char *text)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	e->nrun = 0;
	e->find_n = 0;
	e->find_cur = -1;
	int n = text ? (int)strlen(text) : 0;
	e_splice(e, 0, e->len, text, n);
	e->cursor = 0;
	e->scroll_x = 0.0f;
	e->scroll_y = 0;
	ac_close(e);
}

int
bd_editor_text(bd_id id, char *out, int cap)
{
	struct editor *e = editor_of(id);
	if (!e) return 0;
	if (out && cap > 0) {
		int n = e->len < cap - 1 ? e->len : cap - 1;
		if (n > 0 && e->buf) memcpy(out, e->buf, (size_t)n);
		out[n] = '\0';
	}
	return e->len;
}

int
bd_editor_row_count(bd_id id)
{
	struct editor *e = editor_of(id);
	return e ? e_row_count(e) : 0;
}

int
bd_editor_row_text(bd_id id, int row, char *out, int cap)
{
	struct editor *e = editor_of(id);
	if (!e) return 0;
	int a = e_row_start(e, row);
	int b = e_row_end(e, a);
	int len = b - a;
	if (out && cap > 0) {
		int n = len < cap - 1 ? len : cap - 1;
		if (n > 0) memcpy(out, e->buf + a, (size_t)n);
		out[n] = '\0';
	}
	return len;
}

void
bd_editor_insert_row(bd_id id, int row, const char *s)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	int n = s ? (int)strlen(s) : 0;
	int rc = e_row_count(e);
	if (row >= rc) {
		if (e->len > 0) e_splice(e, e->len, 0, "\n", 1);
		e_splice(e, e->len, 0, s, n);
	} else {
		int off = e_row_start(e, row);
		e_splice(e, off, 0, s, n);
		e_splice(e, off + n, 0, "\n", 1);
	}
}

void
bd_editor_replace_row(bd_id id, int row, const char *s)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	int a = e_row_start(e, row);
	int b = e_row_end(e, a);
	int n = s ? (int)strlen(s) : 0;
	e_splice(e, a, b - a, s, n);
}

void
bd_editor_delete_row(bd_id id, int row)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	int a = e_row_start(e, row);
	int b = e_row_end(e, a);
	if (b < e->len)            /* take the trailing newline */
		b++;
	else if (a > 0)            /* last row: take the preceding newline */
		a--;
	e_splice(e, a, b - a, NULL, 0);
}

void
bd_editor_on_submit(bd_id id, bd_callback_fn fn, void *data)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	e->on_submit = fn;
	e->on_submit_data = data;
}

void
bd_editor_set_completer(bd_id id, bd_completer_fn fn, void *user)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	e->ac_fn = fn;
	e->ac_user = user;
	if (!fn)
		ac_close(e);
}

void
bd_editor_set_complete_min(bd_id id, int chars)
{
	struct editor *e = editor_of(id);
	if (e && chars >= 1)
		e->ac_min = chars;
}

void
bd_editor_set_enter_submits(bd_id id, int on)
{
	struct editor *e = editor_of(id);
	if (e) e->enter_submits = on;
}

int
bd_editor_enter_submits(bd_id id)
{
	struct editor *e = editor_of(id);
	return e ? e->enter_submits : 0;
}

void
bd_editor_set_locked(bd_id id, int locked)
{
	struct editor *e = editor_of(id);
	if (e) e->locked = locked;
}

void
bd_editor_set_monospace(bd_id id, int on)
{
	struct editor *e = editor_of(id);
	if (e) e->mono = on;
}

int
bd_editor_locked(bd_id id)
{
	struct editor *e = editor_of(id);
	return e ? e->locked : 0;
}

void
bd_editor_clear_styles(bd_id id)
{
	struct editor *e = editor_of(id);
	if (e) { e_clear_layer(e, E_LAYER_SYNTAX); e_clear_layer(e, E_LAYER_USER); }
}

void
bd_editor_style_span(bd_id id, int start, int end, bd_rich_style s)
{
	struct editor *e = editor_of(id);
	if (e) e_add_run(e, start, end, E_LAYER_USER, s);
}

void
bd_editor_highlight_row(bd_id id, int row, bd_rich_style s)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	int a = e_row_start(e, row);
	e_add_run(e, a, e_row_end(e, a), E_LAYER_USER, s);
}

void
bd_editor_highlight_span(bd_id id, int row, int col0, int col1, bd_rich_style s)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	int rs = e_row_start(e, row);
	int re = e_row_end(e, rs);
	int a = rs + col0, b = rs + col1;
	if (a < rs) a = rs;
	if (b > re) b = re;
	e_add_run(e, a, b, E_LAYER_USER, s);
}

/* ---- find / replace ---- */

int
bd_editor_find(bd_id id, const char *needle, unsigned flags)
{
	struct editor *e = editor_of(id);
	if (!e) return 0;
	free(e->find_needle);
	e->find_needle = NULL;
	if (needle && needle[0]) {
		int n = (int)strlen(needle);
		e->find_needle = malloc((size_t)n + 1);
		if (e->find_needle)
			memcpy(e->find_needle, needle, (size_t)n + 1);
	}
	e->find_flags = flags;
	int caret = e->cursor;
	e->find_cur = 0;
	e_find_rebuild(e);
	if (e->find_n > 0) {
		int idx = 0;                       /* first match at/after the caret */
		while (idx < e->find_n && e->find_starts[idx] < caret)
			idx++;
		e->find_cur = (idx < e->find_n) ? idx : 0;
		e_find_mark(e);
		e_find_reveal(e);
	}
	return e->find_n;
}

int
bd_editor_find_next(bd_id id)
{
	struct editor *e = editor_of(id);
	if (!e || e->find_n <= 0) return -1;
	e->find_cur = (e->find_cur + 1) % e->find_n;
	e_find_mark(e);
	e_find_reveal(e);
	return e->find_cur;
}

int
bd_editor_find_prev(bd_id id)
{
	struct editor *e = editor_of(id);
	if (!e || e->find_n <= 0) return -1;
	e->find_cur = (e->find_cur - 1 + e->find_n) % e->find_n;
	e_find_mark(e);
	e_find_reveal(e);
	return e->find_cur;
}

int
bd_editor_find_count(bd_id id)
{
	struct editor *e = editor_of(id);
	return e ? e->find_n : 0;
}

int
bd_editor_find_current(bd_id id)
{
	struct editor *e = editor_of(id);
	return e ? e->find_cur : -1;
}

void
bd_editor_find_clear(bd_id id)
{
	struct editor *e = editor_of(id);
	if (!e) return;
	free(e->find_needle);
	e->find_needle = NULL;
	e_clear_layer(e, E_LAYER_FIND);
	e_clear_layer(e, E_LAYER_MARK);
	e->find_n = 0;
	e->find_cur = -1;
}

int
bd_editor_replace(bd_id id, const char *repl)
{
	struct editor *e = editor_of(id);
	if (!e || e->locked || !e->find_needle || e->find_cur < 0 ||
	    e->find_cur >= e->find_n)
		return e ? e->find_cur : -1;
	int nlen = (int)strlen(e->find_needle);
	int s = e->find_starts[e->find_cur];
	int rlen = repl ? (int)strlen(repl) : 0;
	e_splice(e, s, nlen, repl, rlen);
	int caret = s + rlen;              /* land past the replacement */
	e->cursor = caret;
	e_find_rebuild(e);                 /* offsets moved; rescan */
	if (e->find_n > 0) {
		int idx = 0;
		while (idx < e->find_n && e->find_starts[idx] < caret)
			idx++;
		e->find_cur = (idx < e->find_n) ? idx : 0;
		e_find_mark(e);
		e_find_reveal(e);
	} else
		e->find_cur = -1;
	return e->find_cur;
}

int
bd_editor_replace_all(bd_id id, const char *repl)
{
	struct editor *e = editor_of(id);
	if (!e || e->locked || !e->find_needle)
		return 0;
	e_find_rebuild(e);
	int n = e->find_n;
	if (n <= 0)
		return 0;
	int nlen = (int)strlen(e->find_needle);
	int rlen = repl ? (int)strlen(repl) : 0;
	for (int i = n - 1; i >= 0; i--)   /* last-to-first keeps offsets valid */
		e_splice(e, e->find_starts[i], nlen, repl, rlen);
	bd_editor_find_clear(id);
	return n;
}
